spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: bonbonlacorte456@gmail.com
    password: Lacorte215
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database: PostgreSQL
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  
razorpay:
  key:
    id: rzp_test_us_SZMAFSaOJwMCby
    secret: c3ZKFfjuREtMzSKf44F1Oq5L
  callback-url:
      base-url: http://localhost:5173  

admin:
  email: ${admin.email:admin@example.com}
  password: ${admin.password:123456}
  username: ${admin.username:admin}

logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN
    com:
      zaxxer.hikari: WARN
